import Service from '@ember/service';

export default class WordsService extends Service {
  get byLanguage() {
    return {
      en: [
        'Africa',
        'Agent',
        'Air',
        'Alien',
        'Alps',
        'Amazon',
        'Ambulance',
        'America',
        'Angel',
        'Antarctica',
        'Apple',
        'Arm',
        'Atlantis',
        'Australia',
        'Aztec',
        'Back',
        'Ball',
        'Band',
        'Bank',
        'Bar',
        'Bark',
        'Bat',
        'Battery',
        'Beach',
        'Bear',
        'Beat',
        'Bed',
        'Beijing',
        'Bell',
        'Belt',
        'Berlin',
        'Bermuda',
        'Berry',
        'Bill',
        'Block',
        'Board',
        'Bolt',
        'Bomb',
        'Bond',
        'Boom',
        'Boot',
        'Bottle',
        'Bow',
        'Box',
        'Bridge',
        'Brush',
        'Buck',
        'Buffalo',
        'Bug',
        'Bugle',
        'Button',
        'Calf',
        'Canada',
        'Cap',
        'Capital',
        'Car',
        'Card',
        'Carrot',
        'Casino',
        'Cast',
        'Cat',
        'Cell',
        'Centaur',
        'Center',
        'Chair',
        'Change',
        'Charge',
        'Check',
        'Chest',
        'Chick',
        'China',
        'Chocolate',
        'Church',
        'Circle',
        'Cliff',
        'Cloak',
        'Club',
        'Code',
        'Cold',
        'Comic',
        'Compound',
        'Concert',
        'Conductor',
        'Contract',
        'Cook',
        'Copper',
        'Cotton',
        'Court',
        'Cover',
        'Crane',
        'Crash',
        'Cricket',
        'Cross',
        'Crown',
        'Cycle',
        'Czech',
        'Dance',
        'Date',
        'Day',
        'Death',
        'Deck',
        'Degree',
        'Diamond',
        'Dice',
        'Dinosaur',
        'Disease',
        'Doctor',
        'Dog',
        'Draft',
        'Dragon',
        'Dress',
        'Drill',
        'Drop',
        'Duck',
        'Dwarf',
        'Eagle',
        'Egypt',
        'Embassy',
        'Engine',
        'England',
        'Europe',
        'Eye',
        'Face',
        'Fair',
        'Fall',
        'Fan',
        'Fence',
        'Field',
        'Fighter',
        'Figure',
        'File',
        'Film',
        'Fire',
        'Fish',
        'Flute',
        'Fly',
        'Foot',
        'Force',
        'Forest',
        'Fork',
        'France',
        'Game',
        'Gas',
        'Genius',
        'Germany',
        'Ghost',
        'Giant',
        'Glass',
        'Glove',
        'Gold',
        'Grace',
        'Grass',
        'Greece',
        'Green',
        'Ground',
        'Ham',
        'Hand',
        'Hawk',
        'Head',
        'Heart',
        'Helicopter',
        'Himalayas',
        'Hole',
        'Hollywood',
        'Honey',
        'Hood',
        'Hook',
        'Horn',
        'Horse',
        'Horseshoe',
        'Hospital',
        'Hotel',
        'Ice',
        'ICE Cream',
        'India',
        'Iron',
        'Ivory',
        'Jack',
        'Jam',
        'Jet',
        'Jupiter',
        'Kangaroo',
        'Ketchup',
        'Key',
        'Kid',
        'King',
        'Kiwi',
        'Knife',
        'Knight',
        'Lab',
        'Lap',
        'Laser',
        'Lawyer',
        'Lead',
        'Lemon',
        'Leprechaun',
        'Life',
        'Light',
        'Limousine',
        'Line',
        'Link',
        'Lion',
        'Litter',
        'LOCH Ness',
        'Lock',
        'Log',
        'London',
        'Luck',
        'Mail',
        'Mammoth',
        'Maple',
        'Marble',
        'March',
        'Mass',
        'Match',
        'Mercury',
        'Mexico',
        'Microscope',
        'Millionaire',
        'Mine',
        'Mint',
        'Missile',
        'Model',
        'Mole',
        'Moon',
        'Moscow',
        'Mount',
        'Mouse',
        'Mouth',
        'Mug',
        'Nail',
        'Needle',
        'Net',
        'NEW York',
        'Night',
        'Ninja',
        'Note',
        'Novel',
        'Nurse',
        'Nut',
        'Octopus',
        'Oil',
        'Olive',
        'Olympus',
        'Opera',
        'Orange',
        'Organ',
        'Palm',
        'Pan',
        'Pants',
        'Paper',
        'Parachute',
        'Park',
        'Part',
        'Pass',
        'Paste',
        'Penguin',
        'Phoenix',
        'Piano',
        'Pie',
        'Pilot',
        'Pin',
        'Pipe',
        'Pirate',
        'Pistol',
        'Pit',
        'Pitch',
        'Plane',
        'Plastic',
        'Plate',
        'Platypus',
        'Play',
        'Plot',
        'Point',
        'Poison',
        'Pole',
        'Police',
        'Pool',
        'Port',
        'Post',
        'Pound',
        'Press',
        'Princess',
        'Pumpkin',
        'Pupil',
        'Pyramid',
        'Queen',
        'Rabbit',
        'Racket',
        'Ray',
        'Revolution',
        'Ring',
        'Robin',
        'Robot',
        'Rock',
        'Rome',
        'Root',
        'Rose',
        'Roulette',
        'Round',
        'Row',
        'Ruler',
        'Satellite',
        'Saturn',
        'Scale',
        'School',
        'Scientist',
        'Scorpion',
        'Screen',
        'SCUBA Diver',
        'Seal',
        'Server',
        'Shadow',
        'Shakespeare',
        'Shark',
        'Ship',
        'Shoe',
        'Shop',
        'Shot',
        'Sink',
        'Skyscraper',
        'Slip',
        'Slug',
        'Smuggler',
        'Snow',
        'Snowman',
        'Sock',
        'Soldier',
        'Soul',
        'Sound',
        'Space',
        'Spell',
        'Spider',
        'Spike',
        'Spine',
        'Spot',
        'Spring',
        'Spy',
        'Square',
        'Stadium',
        'Staff',
        'Star',
        'State',
        'Stick',
        'Stock',
        'Straw',
        'Stream',
        'Strike',
        'String',
        'Sub',
        'Suit',
        'Superhero',
        'Swing',
        'Switch',
        'Table',
        'Tablet',
        'Tag',
        'Tail',
        'Tap',
        'Teacher',
        'Telescope',
        'Temple',
        'Theater',
        'Thief',
        'Thumb',
        'Tick',
        'Tie',
        'Time',
        'Tokyo',
        'Tooth',
        'Torch',
        'Tower',
        'Track',
        'Train',
        'Triangle',
        'Trip',
        'Trunk',
        'Tube',
        'Turkey',
        'Undertaker',
        'Unicorn',
        'Vacuum',
        'Van',
        'Vet',
        'Wake',
        'Wall',
        'War',
        'Washer',
        'Washington',
        'Watch',
        'Water',
        'Wave',
        'Web',
        'Well',
        'Whale',
        'Whip',
        'Wind',
        'Witch',
        'Worm',
        'Yard',
      ],
      de: [
        'Absteige ',
        'Absturz ',
        'Abzug',
        'Ader ',
        'Affäre ',
        'Aktion ',
        'Alarm',
        'Altar ',
        'Amsterdam ',
        'Angel',
        'Anstoß',
        'Antrieb ',
        'Araber',
        'Attentat',
        'Ausschnitt',
        'Auster ',
        'Bagger',
        'Ballon ',
        'Banane ',
        'Bauch ',
        'Befriedigung ',
        'Bescheinigung ',
        'Bestechung ',
        'Betrüger ',
        'Beziehung ',
        'Biene',
        'Biest',
        'Binde ',
        'Blase',
        'Blondine ',
        'Blümchen ',
        'Bolzen ',
        'Bondage',
        'Bong',
        'Bordell',
        'Braun ',
        'Bruch ',
        'Bruder',
        'Busen ',
        'Callboy',
        'Club ',
        'Cocktail ',
        'Creme',
        'Dampfer ',
        'Dealer',
        'Dèjá- Vu',
        'Delta ',
        'Diät',
        'Diener ',
        'Dildo ',
        'Domina ',
        'Dreier ',
        'Droge ',
        'Drohne ',
        'Dschungel ',
        'Dübel ',
        'Dusche',
        'Ehe',
        'Ei',
        'Eichel',
        'Eifersucht ',
        'Ekel',
        'Ekstase',
        'Elefant',
        'Empfängnis',
        'Entgleisung ',
        'Erbe ',
        'Erdbeere ',
        'Erfahrung',
        'Eroberung',
        'Erotik ',
        'Erpressung ',
        'Erregung ',
        'Esel ',
        'Experiment',
        'Falle ',
        'Fantasie ',
        'Faschist ',
        'Faust',
        'Fehler ',
        'Feigling',
        'Feind',
        'Fetisch ',
        'Feuchtgebiet ',
        'Feuerwerk ',
        'Filmriss',
        'Finsternis',
        'Fleisch ',
        'Flucht',
        'Folter ',
        'Freiheit',
        'Freude',
        'Freundin ',
        'Frieden ',
        'Frosch ',
        'Fuge ',
        'Fummeln',
        'Gedächtnis ',
        'Geisel ',
        'Gelage',
        'Geld ',
        'Geschlecht ',
        'Geschütz ',
        'Gewalt ',
        'Gewerbe ',
        'Gier',
        'Gigolo',
        'Glatze ',
        'Glied ',
        'Gourmet ',
        'Grenze',
        'Gummi ',
        'Gurke ',
        'Haar',
        'Hacke',
        'Haft',
        'Hammer ',
        'Handarbeit ',
        'Handel ',
        'Handschellen ',
        'Handtuch',
        'Hass',
        'Haut',
        'Hehler ',
        'Hengst ',
        'Herpes',
        'Heu ',
        'Himmel ',
        'Hintern ',
        'Hof',
        'Höhepunkt ',
        'Hölle',
        'Holz',
        'Horror',
        'Hose ',
        'Hubraum',
        'Hunger ',
        'Hütte',
        'Jaguar',
        'Joystick ',
        'Jucken',
        'Jungfrau ',
        'Junggeselle ',
        'Juwelen',
        'Kabine ',
        'Käfig ',
        'Kamasutra ',
        'Kanone',
        'Katastrophe ',
        'Kaviar ',
        'Keller',
        'Kessel ',
        'Kette ',
        'Keule ',
        'Kiez ',
        'Kirsche',
        'Kiste ',
        'Klempner',
        'Kneipe',
        'Knete ',
        'Kondition',
        'Korruption ',
        'Köttel',
        'Krampf',
        'Kraut',
        'Kuba',
        'Kult ',
        'Kunst',
        'Kurven ',
        'Kurzer ',
        'Kuss ',
        'Lache',
        'Latex',
        'Latte',
        'Lawine ',
        'Libido ',
        'Liebe',
        'Likör',
        'Limo',
        'Locken ',
        'Losung',
        'Lotus ',
        'Lümmel ',
        'Lust ',
        'Lutscher',
        'Macho ',
        'Macht',
        'Mafia',
        'Magazin',
        'Make-Up',
        'Mallorca ',
        'Martini ',
        'Maske',
        'Massage',
        'Massaker ',
        'Matratze ',
        'Mauer',
        'Messie ',
        'Metro ',
        'Milch',
        'Missionar',
        'Mist ',
        'Mobbing',
        'Molotow ',
        'Mönch',
        'Monster ',
        'Möpse',
        'Mord ',
        'Müdigkeit ',
        'Munition ',
        'Mut ',
        'Mütze ',
        'Nachlass',
        'Nase ',
        'Neid ',
        'Nippel',
        'Nonne',
        'Nudel ',
        'Nutte',
        'Nymphe',
        'Oma',
        'Opfer ',
        'Orgie',
        'Paar ',
        'Palme',
        'Panik ',
        'Panzer ',
        'Papst',
        'Pariser ',
        'Partei ',
        'Pelz',
        'Perle ',
        'Pfirsich ',
        'Pflaume',
        'Pforte ',
        'Pickel',
        'Piercing',
        'Pille',
        'Pilz',
        'Porno ',
        'Praktikant ',
        'Predigt ',
        'Probe',
        'Puder ',
        'Pumpe ',
        'Puppe',
        'Push-Up',
        'Rakete',
        'Rammler ',
        'Rassist ',
        'Rasur',
        'Raub',
        'Rauch',
        'Raupe ',
        'Rausch',
        'Regel ',
        'Regenbogen',
        'Reibe',
        'Reichtum',
        'Reiter ',
        'Reiz ',
        'Respekt',
        'Ritze ',
        'Rohr ',
        'Rollenspiel ',
        'Rosette',
        'Rotlicht',
        'Rudel ',
        'Ruhe',
        'Saft',
        'Sahne ',
        'Samen',
        'Sauna ',
        'Scham ',
        'Schinken',
        'Schlacht ',
        'Schlag ',
        'Schlamm ',
        'Schleier',
        'Schluck ',
        'Schluss',
        'Schmerz',
        'Schnalle',
        'Schnauzer ',
        'Schnecke ',
        'Schnitt',
        'Schraube ',
        'Schuld ',
        'Schütze ',
        'Schwalbe',
        'Schwanz ',
        'Schwarz ',
        'Schwein',
        'Schweiß',
        'Schwellung ',
        'Schwester ',
        'Seide ',
        'Seife ',
        'Sekt',
        'Service',
        'Sex ',
        'Show',
        'Sirene ',
        'Sitte',
        'Skandal ',
        'Sklave ',
        'Solo',
        'Spagat',
        'Spanner ',
        'Speichel ',
        'Spielzeug ',
        'Spritz ',
        'Spritze ',
        'Spur',
        'Stab',
        'Ständer',
        'Stellung',
        'Stiefel',
        'Stiletto',
        'Stoff ',
        'Stolz',
        'Stopp',
        'Strahl ',
        'Streifen ',
        'Stress',
        'Strich ',
        'Strip ',
        'Stroh',
        'Sucht ',
        'Sünde',
        'Tablette ',
        'Tabu',
        'Talent',
        'Tatort',
        'Telefon ',
        'Teppich ',
        'Tequila ',
        'Test ',
        'Thailand',
        'Thron ',
        'Tiger',
        'Trick',
        'Trikot',
        'Tugend ',
        'Tüte',
        'Unfall',
        'Veilchen ',
        'Vene',
        'Venus ',
        'Verbrechen',
        'Verdienst ',
        'Verfahren ',
        'Verhütung ',
        'Verkehr',
        'Verlängerung',
        'Vermächtnis ',
        'Verschwörung ',
        'Vibration ',
        'Video',
        'Vorbau',
        'Vulkan',
        'Wachs',
        'Waffe',
        'Warze',
        'Wäsche ',
        'Wehen',
        'Wein',
        'Weiss',
        'Whisky ',
        'Widerstand',
        'Wodka',
        'Wolllust ',
        'Wrack ',
        'Wurst',
        'Zange ',
        'Zehe',
        'Zigarette',
        'Zigarre ',
        'Zocker ',
        'Zölibat',
        'Zorn',
        'Zucht ',
        'Zuhälter',
        'Zunge ',
        'Zwilling ',
        'Zwitter',
      ],
    };
  }
}
