import Service from '@ember/service';

export default class WordsService extends Service {
  list = [
    {
      title: 'English',
      words:
        'Africa,Agent,Air,Alien,Alps,Amazon,Ambulance,America,Angel,Antarctica,Apple,Arm,Atlantis,Australia,Aztec,Back,Ball,Band,Bank,Bar,Bark,Bat,Battery,Beach,Bear,Beat,Bed,Beijing,Bell,Belt,Berlin,Bermuda,Berry,Bill,Block,Board,Bolt,Bomb,Bond,Boom,Boot,Bottle,Bow,Box,Bridge,Brush,Buck,Buffalo,Bug,Bugle,Button,Calf,Canada,Cap,Capital,Car,Card,Carrot,Casino,Cast,Cat,Cell,Centaur,Center,Chair,Change,Charge,Check,Chest,Chick,China,Chocolate,Church,Circle,Cliff,Cloak,Club,Code,Cold,Comic,Compound,Concert,Conductor,Contract,Cook,Copper,Cotton,Court,Cover,Crane,Crash,Cricket,Cross,Crown,Cycle,Czech,Dance,Date,Day,Death,Deck,Degree,Diamond,Dice,Dinosaur,Disease,Doctor,Dog,Draft,Dragon,Dress,Drill,Drop,Duck,Dwarf,Eagle,Egypt,Embassy,Engine,England,Europe,Eye,Face,Fair,Fall,Fan,Fence,Field,Fighter,Figure,File,Film,Fire,Fish,Flute,Fly,Foot,Force,Forest,Fork,France,Game,Gas,Genius,Germany,Ghost,Giant,Glass,Glove,Gold,Grace,Grass,Greece,Green,Ground,Ham,Hand,Hawk,Head,Heart,Helicopter,Himalayas,Hole,Hollywood,Honey,Hood,Hook,Horn,Horse,Horseshoe,Hospital,Hotel,Ice,ICE Cream,India,Iron,Ivory,Jack,Jam,Jet,Jupiter,Kangaroo,Ketchup,Key,Kid,King,Kiwi,Knife,Knight,Lab,Lap,Laser,Lawyer,Lead,Lemon,Leprechaun,Life,Light,Limousine,Line,Link,Lion,Litter,LOCH Ness,Lock,Log,London,Luck,Mail,Mammoth,Maple,Marble,March,Mass,Match,Mercury,Mexico,Microscope,Millionaire,Mine,Mint,Missile,Model,Mole,Moon,Moscow,Mount,Mouse,Mouth,Mug,Nail,Needle,Net,NEW York,Night,Ninja,Note,Novel,Nurse,Nut,Octopus,Oil,Olive,Olympus,Opera,Orange,Organ,Palm,Pan,Pants,Paper,Parachute,Park,Part,Pass,Paste,Penguin,Phoenix,Piano,Pie,Pilot,Pin,Pipe,Pirate,Pistol,Pit,Pitch,Plane,Plastic,Plate,Platypus,Play,Plot,Point,Poison,Pole,Police,Pool,Port,Post,Pound,Press,Princess,Pumpkin,Pupil,Pyramid,Queen,Rabbit,Racket,Ray,Revolution,Ring,Robin,Robot,Rock,Rome,Root,Rose,Roulette,Round,Row,Ruler,Satellite,Saturn,Scale,School,Scientist,Scorpion,Screen,SCUBA Diver,Seal,Server,Shadow,Shakespeare,Shark,Ship,Shoe,Shop,Shot,Sink,Skyscraper,Slip,Slug,Smuggler,Snow,Snowman,Sock,Soldier,Soul,Sound,Space,Spell,Spider,Spike,Spine,Spot,Spring,Spy,Square,Stadium,Staff,Star,State,Stick,Stock,Straw,Stream,Strike,String,Sub,Suit,Superhero,Swing,Switch,Table,Tablet,Tag,Tail,Tap,Teacher,Telescope,Temple,Theater,Thief,Thumb,Tick,Tie,Time,Tokyo,Tooth,Torch,Tower,Track,Train,Triangle,Trip,Trunk,Tube,Turkey,Undertaker,Unicorn,Vacuum,Van,Vet,Wake,Wall,War,Washer,Washington,Watch,Water,Wave,Web,Well,Whale,Whip,Wind,Witch,Worm,Yard',
    },
    {
      title: 'Deutsch (ab 18)',
      words:
        'Absteige,Absturz,Abzug,Ader,Affäre,Aktion,Alarm,Altar,Amsterdam,Angel,Anstoß,Antrieb,Araber,Attentat,Ausschnitt,Auster,Bagger,Ballon,Banane,Bauch,Befriedigung,Bescheinigung,Bestechung,Betrüger,Beziehung,Biene,Biest,Binde,Blase,Blondine,Blümchen,Bolzen,Bondage,Bong,Bordell,Braun,Bruch,Bruder,Busen,Callboy,Club,Cocktail,Creme,Dampfer,Dealer,Dèjá- Vu,Delta,Diät,Diener,Dildo,Domina,Dreier,Droge,Drohne,Dschungel,Dübel,Dusche,Ehe,Ei,Eichel,Eifersucht,Ekel,Ekstase,Elefant,Empfängnis,Entgleisung,Erbe,Erdbeere,Erfahrung,Eroberung,Erotik,Erpressung,Erregung,Esel,Experiment,Falle,Fantasie,Faschist,Faust,Fehler,Feigling,Feind,Fetisch,Feuchtgebiet,Feuerwerk,Filmriss,Finsternis,Fleisch,Flucht,Folter,Freiheit,Freude,Freundin,Frieden,Frosch,Fuge,Fummeln,Gedächtnis,Geisel,Gelage,Geld,Geschlecht,Geschütz,Gewalt,Gewerbe,Gier,Gigolo,Glatze,Glied,Gourmet,Grenze,Gummi,Gurke,Haar,Hacke,Haft,Hammer,Handarbeit,Handel,Handschellen,Handtuch,Hass,Haut,Hehler,Hengst,Herpes,Heu,Himmel,Hintern,Hof,Höhepunkt,Hölle,Holz,Horror,Hose,Hubraum,Hunger,Hütte,Jaguar,Joystick,Jucken,Jungfrau,Junggeselle,Juwelen,Kabine,Käfig,Kamasutra,Kanone,Katastrophe,Kaviar,Keller,Kessel,Kette,Keule,Kiez,Kirsche,Kiste,Klempner,Kneipe,Knete,Kondition,Korruption,Köttel,Krampf,Kraut,Kuba,Kult,Kunst,Kurven,Kurzer,Kuss,Lache,Latex,Latte,Lawine,Libido,Liebe,Likör,Limo,Locken,Losung,Lotus,Lümmel,Lust,Lutscher,Macho,Macht,Mafia,Magazin,Make-Up,Mallorca,Martini,Maske,Massage,Massaker,Matratze,Mauer,Messie,Metro,Milch,Missionar,Mist,Mobbing,Molotow,Mönch,Monster,Möpse,Mord,Müdigkeit,Munition,Mut,Mütze,Nachlass,Nase,Neid,Nippel,Nonne,Nudel,Nutte,Nymphe,Oma,Opfer,Orgie,Paar,Palme,Panik,Panzer,Papst,Pariser,Partei,Pelz,Perle,Pfirsich,Pflaume,Pforte,Pickel,Piercing,Pille,Pilz,Porno,Praktikant,Predigt,Probe,Puder,Pumpe,Puppe,Push-Up,Rakete,Rammler,Rassist,Rasur,Raub,Rauch,Raupe,Rausch,Regel,Regenbogen,Reibe,Reichtum,Reiter,Reiz,Respekt,Ritze,Rohr,Rollenspiel,Rosette,Rotlicht,Rudel,Ruhe,Saft,Sahne,Samen,Sauna,Scham,Schinken,Schlacht,Schlag,Schlamm,Schleier,Schluck,Schluss,Schmerz,Schnalle,Schnauzer,Schnecke,Schnitt,Schraube,Schuld,Schütze,Schwalbe,Schwanz,Schwarz,Schwein,Schweiß,Schwellung,Schwester,Seide,Seife,Sekt,Service,Sex,Show,Sirene,Sitte,Skandal,Sklave,Solo,Spagat,Spanner,Speichel,Spielzeug,Spritz,Spritze,Spur,Stab,Ständer,Stellung,Stiefel,Stiletto,Stoff,Stolz,Stopp,Strahl,Streifen,Stress,Strich,Strip,Stroh,Sucht,Sünde,Tablette,Tabu,Talent,Tatort,Telefon,Teppich,Tequila,Test,Thailand,Thron,Tiger,Trick,Trikot,Tugend,Tüte,Unfall,Veilchen,Vene,Venus,Verbrechen,Verdienst,Verfahren,Verhütung,Verkehr,Verlängerung,Vermächtnis,Verschwörung,Vibration,Video,Vorbau,Vulkan,Wachs,Waffe,Warze,Wäsche,Wehen,Wein,Weiss,Whisky,Widerstand,Wodka,Wolllust,Wrack,Wurst,Zange,Zehe,Zigarette,Zigarre,Zocker,Zölibat,Zorn,Zucht,Zuhälter,Zunge,Zwilling,Zwitter',
    },
    {
      title: 'Spanish',
      words:
        'Abogado,Aceite,África,Agente,Agua,Águila,Aguja,Agujero,Aire,Alemania,Algodón,Alianza,Alpes,Ambulancia,América,Ángel,Anillo,Antártida,Antorcha,Araña,Archivo,Arco,Argentina,Artículo,As,Atlántida,Azteca,Baile,Bala,Ballena,Banco,Banda,Baño,Barco,Barra,Batería,Berlín,Bermudas,Bicho,Blanco,Bloque,Boca,Bola,Bolsa,Bomba,Bosque,Bota,Botella,Botón,Brazo,Bruja,Caballero,Caballo,Cabeza,Cabina,Cabo,Cactus,Cadena,Caja,Cama,Cámara,Cambio,Campana,Campo,Canal,Canguro,Canto,Caña,Capa,Capital,Caqui,Cara,Caravana,Carga,Carrera,Carro,Carta,Casco,Casino,Caza,Cementerio,Centauro,Centro,Cervantes,Checo,Chocolate,Choque,Chuleta,Científico,Cinta,Cinturón,Círculo,Clase,Coche,Cocinero,Coco,Código,Cola,Cólera,Columna,Cometa,Compás,Concierto,Conejo,Contrabandista,Copa,Corazón,Corneta,Corona,Corredor,Corriente,Corte,Cresta,Cromo,Cruz,Cuadro,Cuarto,Cubierta,Cubo,Cuchillo,Cuello,Cuerda,Cuerno,Cura,Dama,Delta,Destino,Día,Diamante,Diana,Diario,Diente,Dinosaurio,Disco,Don,Dragón,Duende,Egipto,Embajada,Emperador,Enano,Enfermedad,Enfermera,Enlace,Escorpión,Espacio,Espía,Estación,Estadio,Estado,Estrella,Estudio,Etiqueta,Europa,Extraterrestre,Falda,Fantasma,Faro,Ficha,Fiesta,Figura,Flauta,Flecha,Foso,Francia,Frente,Fuego,Fuente,Fuerza,Furgoneta,Gancho,Gato,Genio,Gigante,Golfo,Golondrina,Golpe,Goma,Góndola,Gota,Grado,Granada,Grano,Grecia,Grifo,Guante,Guardia,Guerra,Gusano,Helado,Helicóptero,Hielo,Hierba,Hoja,Hollywood,Horca,Hospital,Hotel,Iglesia,Imán,India,Índice,Inglaterra,Italia,Jarra,Judía,Juicio,Kiwi,Ladrón,Lago ness,Láser,Látigo,Lengua,León,Libra,Lima,Limusina,Línea,Lista,Llama,Llave,Lomo,Londres,Luna,Luz,Maestro,Magia,Malta,Mancha,Mando,Manga,Mango,Mano,Manzana,Mañana,Marca,Marcha,Marfil,Masa,Máscara,Mazo,Médico,Mercurio,Mesa,Metro,México,Micro,Microscopi,Mielo,Millonario,Mina,Misil,Modelo,Módulo,Monitor,Mono,Mortero,Moscú,Motor,Muelle,Muerte,Muñeca,Muro,Naranja,Nave,Nieve,Nilo,Ninja,Noche,Nota,Nudo,Nueva york,Obra,Ojo,Ola,Olimpo,Ópera,Orden,Órgano,Ornitorrinco,Oro,Oso,Pala,Palma,Pantalla,Papel,Paracaídas,Pase,Paso,Pasta,Pastel,Pavo,Pekín,Película,Pelotón,Pendiente,Perro,Pez,Pico,Pie,Pieza,Pila,Piloto,Pincho,Pingüino,Pinta,Piña,Pirámide,Pirata,Pista,Pistola,Placa,Plano,Planta,Plátano,Playa,Plomo,Pluma,Policía,Polo,Portada,Portero,Potro,Prensa,Prima,Princesa,Puente,Puerto,Pulpo,Pulso,Punta,Punto,Radio,Rascacielos,Ratón,Rayo,Red,Regla,Reina,Reserva,Revolución,Rey,Robot,Rojo,Roma,Ronda,Rosa,Ruleta,Sable,Sáhara,Salsa,Satélite,Saturno,Señal,Serie,Serpiente,Sierra,Silla,Sirena,Sobre,Soldado,Submarinista,Suerte,Superhéroe,Tabla,Tableta,Taco,Tacto,Talón,Tanque,Tapa,Tarde,Teatro,Teclado,Telescopio,Testigo,Tiempo,Tienda,Tierra,Tokio,Topo,Torre,Trama,Tronco,Tubería,Tubo,Unicornio,Vacío,Vado,Vampiro,Vela,Veneno,Venus,Vestido,Vida,Vidrio,Viento,Yema,Zanahoria,Zapato',
    },
  ];
}
